Add a make log

diff --git a/openwrtbuilder b/openwrtbuilder
--- a/openwrtbuilder
+++ b/openwrtbuilder
@@ -751,8 +751,8 @@ from_source() {
   make_opts+=("-j$JOBS")
 
   # Make image
-  if ! execute ionice -c2 -n7 nice -n19 make "${make_opts[@]}" BIN_DIR="$BIN_DIR" world; then
-    echo "Error: make failed"
+  if ! ionice -c2 -n7 nice -n19 make "${make_opts[@]}" BIN_DIR="$BIN_DIR" world 2>&1 | tee "$BUILD_DIR/make.log"; then
+    echo "Error: make failed (see $BUILD_DIR/make.log)"
     return 1
   fi
 
