Integrate BINDIR

diff --git a/openwrtbuilder b/openwrtbuilder
--- a/openwrtbuilder
+++ b/openwrtbuilder
@@ -443,26 +443,26 @@ makeImage() {
     debug "${FUNCNAME[0]}"
 
     # Reuse the existing output
-    if [[ -d "$BUILDDIR" ]]; then
-        if askOk "$BUILDDIR exists. Rebuild?"; then
-            rm -rf "$BUILDDIR"
+    if [[ -d "$BINDIR" ]]; then
+        if askOk "$BINDIR exists. Rebuild?"; then
+            rm -rf "$BINDIR"
         else
             return 0
         fi
     fi
 
-    [[ ! -d "$BUILDDIR" ]] && mkdir -p "$BUILDDIR"
+    [[ -d "$BUILDDIR" ]] || mkdir -p "$BUILDDIR"
 
     if ! make image \
-            BIN_DIR="$BINDIR" \
-            PROFILE="${P_ARR[profile]}" \
-            PACKAGES="${P_ARR[packages]}" \
-            FILES="${FILESDIR}" \
-            --directory="$BUILDDIR" \
-            --jobs="$(nproc)"  \
-            > make.log; then
-        echo "Make image failed!"
-        exit 1
+        BIN_DIR="$BINDIR" \
+        PROFILE="${P_ARR[profile]}" \
+        PACKAGES="${P_ARR[packages]}" \
+        FILES="${FILESDIR}" \
+        --directory="$BUILDDIR" \
+        --jobs="$(nproc)"  \
+        > "$BUILDDIR/make.log"; then
+            echo "Make image failed!"
+            exit 1
     fi
 }
 
@@ -477,7 +477,7 @@ flashImage() {
         exit 1
     fi
 
-    # TODO Roughly chooses the correct image
+    # TODO Roughly choose the correct image
     if [[ -f "$FACTORYIMGGZ" ]]; then
         img_gz="$FACTORYIMGGZ"
         img="$FACTORYIMG"
